name: Update Lapis Armor Sounds

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sox ffmpeg curl unzip

      - name: Prepare directories
        run: |
          mkdir -p RP/sounds/armor
          mkdir -p wav
          mkdir -p tools

      - name: Download FSB files from Bedrock-samples
        run: |
          for i in {1..6}; do
            curl -L -o RP/sounds/armor/equip_iron$i.fsb \
              https://raw.githubusercontent.com/mojang/bedrock-samples/main/resource_pack/sounds/armor/equip_iron$i.fsb
          done

      - name: Copy FSB to lapislazuli
        run: |
          for i in {1..6}; do
            cp RP/sounds/armor/equip_iron$i.fsb RP/sounds/armor/equip_lapislazuli$i.fsb
          done

      - name: Download vgmstream static binary
        run: |
          curl -L -o tools/vgmstream-cli.zip https://ci.appveyor.com/api/buildjobs/xyz/artifacts/vgmstream-cli.zip
          unzip tools/vgmstream-cli.zip -d tools
          chmod +x tools/vgmstream-cli

      - name: Convert FSB to WAV and apply Lapis effect
        run: |
          for i in {1..6}; do
            in_fsb="RP/sounds/armor/equip_iron$i.fsb"
            out_wav="wav/equip_lapislazuli$i.wav"
            ./tools/vgmstream-cli "$in_fsb" -o "$out_wav"
            sox "$out_wav" "$out_wav" pitch 200 reverb 50
          done

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add RP/sounds/armor/equip_lapislazuli*.fsb wav/*
          git commit -m "Update lapislazuli armor sounds (FSB + WAV)"
          git push
